#!/usr/bin/env bash
### end common-components/bash-shebang

info() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

info "Updating apt-get"
    sudo apt-get update

info "Installing git"
  sudo apt install -y git

info "Installing common libraries and gem dependencies"
  sudo apt install -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev \
                      libqtwebkit-dev libreadline-dev gnupg2 gawk autoconf \
                      automake bison libffi-dev libgdbm-dev libncurses5-dev \
                      libtool libyaml-dev libgmp-dev libssl-dev build-essential

info "Installing common tools"
  sudo apt install -y libsqlite3-dev sqlite3 tmux imagemagick curl zsh

info "Installing RVM"
  command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  \curl -sSL https://get.rvm.io | bash -s stable --ruby --gems=bundler

info "Configuring Gem & Bundler for faster, parallel gem installation "
  echo 'gem: --no-document --no-ri --no-rdoc' > ~/.gemrc
  mkdir ~/.bundle
  echo 'BUNDLE_--JOBS: "5"' > ~/.bundle/config

info "Installing node and yarn"
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt-get update && sudo apt-get install -y yarn nodejs
  node -v; yarn -v

info "Installing python"
  sudo apt-get install -y python python3 python-setuptools python-dev python-pip python3-pip
  sudo pip install --upgrade virtualenv

info "Installing the heroku-config plugin to pull config variables locally to be used as ENV variables "
  heroku plugins:install git://github.com/ddollar/heroku-config.git

info "Installing chrome "
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  sudo apt-get update && sudo apt-get install google-chrome-stable

info "Installing docker"
  sudo groupadd docker
  sudo usermod -aG docker $USER
  sudo gpasswd -a $USER docker
  snap install docker
  sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  docker -v
  docker-compose -v

info "Installing Heroku CLI client "
  sudo snap install heroku --classic
  heroku login

info "Installing Shopify Theme kit"
  curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python

info "Preparing ssh key for github"
    info "What is your github email?"
    read -r user_email
    ssh-keygen -t rsa -b 4096 -C $user_email
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa

info "Clipping the key into clipboard"
    sudo apt-get install -y xclip
    xclip -sel clip < ~/.ssh/id_rsa.pub

info "Installing oh-my-zsh "
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    chsh -s $(which zsh)


